spring:
   application:
      name: report-repository
   rabbitmq:
      addresses: rabbitmq
   cloud:
      stream:
        bindings:
          products:
            destination: productsTopic
            content-type: application/json
            group: report-repository
          orders:
            destination: ordersTopic
            content-type: application/json
            group: report-repository
          statusUpdates:
            destination: statusUpdatesTopic
            content-type: application/json
            group: report-repository
          reportFiles:
            destination: reportFileTopic
            content-type: text/plain
            group: report-repository
          rabbit:
            binder:
              nodes: rabbitmq
              adminAddresses: rabbitmq
security:
  oauth2:
    resource:
      userInfoUri: http://identity-service:8080/user		
logging:
    level:
      org.springframework: INFO
      org.springframework.security: DEBUG